# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: jquery-modal-rails 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "jquery-modal-rails".freeze
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Dominik Fijas".freeze]
  s.date = "2018-06-20"
  s.description = "TODO: longer description of your gem".freeze
  s.email = "dominik.fijas@nedap.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "demoapp/Gemfile",
    "demoapp/README.rdoc",
    "demoapp/Rakefile",
    "demoapp/app/assets/images/rails.png",
    "demoapp/app/assets/javascripts/application.js",
    "demoapp/app/assets/javascripts/users.js.coffee",
    "demoapp/app/assets/stylesheets/application.css",
    "demoapp/app/assets/stylesheets/scaffolds.css.scss",
    "demoapp/app/assets/stylesheets/users.css.scss",
    "demoapp/app/controllers/application_controller.rb",
    "demoapp/app/controllers/users_controller.rb",
    "demoapp/app/helpers/application_helper.rb",
    "demoapp/app/helpers/users_helper.rb",
    "demoapp/app/models/user.rb",
    "demoapp/app/views/layouts/application.html.erb",
    "demoapp/app/views/users/_form.html.erb",
    "demoapp/app/views/users/edit.html.erb",
    "demoapp/app/views/users/index.html.erb",
    "demoapp/app/views/users/new.html.erb",
    "demoapp/app/views/users/show.html.erb",
    "demoapp/config.ru",
    "demoapp/config/application.rb",
    "demoapp/config/boot.rb",
    "demoapp/config/database.yml",
    "demoapp/config/environment.rb",
    "demoapp/config/environments/development.rb",
    "demoapp/config/environments/production.rb",
    "demoapp/config/environments/test.rb",
    "demoapp/config/initializers/backtrace_silencers.rb",
    "demoapp/config/initializers/inflections.rb",
    "demoapp/config/initializers/mime_types.rb",
    "demoapp/config/initializers/secret_token.rb",
    "demoapp/config/initializers/session_store.rb",
    "demoapp/config/initializers/wrap_parameters.rb",
    "demoapp/config/locales/en.yml",
    "demoapp/config/routes.rb",
    "demoapp/db/development.sqlite3",
    "demoapp/db/migrate/20120621084323_create_users.rb",
    "demoapp/db/schema.rb",
    "demoapp/db/seeds.rb",
    "demoapp/db/test.sqlite3",
    "demoapp/doc/README_FOR_APP",
    "demoapp/log/development.log",
    "demoapp/public/404.html",
    "demoapp/public/422.html",
    "demoapp/public/500.html",
    "demoapp/public/favicon.ico",
    "demoapp/public/robots.txt",
    "demoapp/script/rails",
    "demoapp/test/fixtures/users.yml",
    "demoapp/test/functional/users_controller_test.rb",
    "demoapp/test/performance/browsing_test.rb",
    "demoapp/test/test_helper.rb",
    "demoapp/test/unit/helpers/users_helper_test.rb",
    "demoapp/test/unit/user_test.rb",
    "jquery-modal-rails.gemspec",
    "lib/jquery-modal-rails.rb",
    "lib/jquery/modal/filters.rb",
    "lib/jquery/modal/filters/ajax_request_filters.rb",
    "lib/jquery/modal/helpers.rb",
    "lib/jquery/modal/helpers/link_helpers.rb",
    "lib/jquery/modal/rails.rb",
    "lib/jquery/modal/rails/engine.rb",
    "lib/jquery/modal/rails/version.rb",
    "spec/jquery/modal/link_helpers_spec.rb",
    "spec/spec_helper.rb",
    "vendor/assets/images/close.png",
    "vendor/assets/images/spinner.gif",
    "vendor/assets/javascripts/jquery.modal.js",
    "vendor/assets/stylesheets/jquery.modal.css.scss"
  ]
  s.homepage = "http://github.com/nedap/jquery-modal-rails".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.12".freeze
  s.summary = "TODO: one-line summary of your gem".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jquery-rails>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      s.add_dependency(%q<jquery-rails>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<jquery-rails>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

